create table if not exists users (
    id bigint generated by default as identity not null,
    name varchar(255) not null,
    email varchar(255) not null,
    constraint pk_user primary key (id),
    constraint uq_user_email unique (email)
);

create table if not exists items (
    id bigint generated by default as identity not null,
    name varchar(255) not null,
    description varchar(255) not null,
    is_available boolean not null,
    owner_id bigint not null references users(id),
    -- request_id bigint not null references requests(id),
    constraint pk_item primary key (id)
);

create table if not exists bookings (
    id bigint generated by default as identity not null,
    start_date timestamp without time zone not null,
    end_date timestamp without time zone not null,
    item_id bigint not null references items(id),
    booker_id bigint not null references users(id),
    status varchar(50) not null,
    constraint pk_booking primary key (id)
);

create table if not exists comments (
    id bigint generated by default as identity not null,
    text varchar(255) not null,
    item_id bigint not null references items(id),
    author_id bigint not null references users(id),
    created timestamp without time zone not null,
    constraint pk_comments primary key (id)
);